#!/bin/sh

# mkdir + cd in one step

dmk() { mkdir -p "$@" && cd "$_" || printf 'Cannot not create directory\n' 1>&2 ; }

# get alias output

pt() { $PAGER "$(command -v ""$1"")"; }

# tag directories so you can come back later

mark() {
  if [ "$#" -eq 1 ]; then
    if [ ! -L "${TMPDIR:-/tmp}/dmark_$1" ]; then
      printf 'Error: Cannot find %s mark\n' "$1" 1>&2
      return 1
    fi
  elif [ "$#" -eq 2 ]; then
    if [ -d "$2" ]; then
      rm --force "${TMPDIR:-/tmp}/dmark_$1"
      ln --symbolic "$PWD/$2" "${TMPDIR:-/tmp}/dmark_$1"
    else
      printf 'Error: Second argument %s should be a directory\n' "$2" 1>&2
      return 1
    fi
  else
    printf 'We need one or two arguments, {tag} and (optianlly) {directory}\n' 1>&2
    return 1
  fi

  cd -P "${TMPDIR:-/tmp}/dmark_$1"
  touch -c "${TMPDIR:-/tmp}/dmark_$1"
}
