#!/bin/sh

# Waiting for a command
if test "$SSH_CLIENT" -o "$SSH_TTY"; then
  PS1="[$USER@$(uname -n)]"' ${PWD##*/}$ '
else
  PS1='${PWD##*/}$ '
fi
# Waiting to complete command
PS2='> '  

# modify workstation (terminal) parameters
. "${XDG_CONFIG_HOME:-$HOME/.config}/sh/tty"

# aliases
. "${XDG_CONFIG_HOME:-$HOME/.config}/sh/aliases"

# functions
. "${XDG_CONFIG_HOME:-$HOME/.config}/sh/functions"
