#!/bin/sh

# Waiting for a command
if test "$SSH_CLIENT" -o "$SSH_TTY"; then
    PS1="[$USER@$(uname -n)]"' ${PWD##*/}$ '
else
    PS1='${PWD##*/}$ '
fi
# Waiting to complete command
PS2='> '  


# Modify workstation (terminal) behavior
# Give back c-s and c-q. Check out XOFF and XON:(https://en.wikipedia.org/wiki/Software_flow_control)
stty -ixon  -ixoff   

# Aliases
alias cal='cal --monday'
alias diff='diff --color=auto'
alias grep='grep --color=auto' # https://beyondgrep.com/feature-comparison/
alias ssh-keygen='ssh-keygen -o -a 100 -t ed25519'

# - _
# + - - go back to last directory
# - ,
# - a
alias b='$BROWSER'
# - c
alias d=trash
alias e='$EDITOR'
alias f=flush
alias g=git
alias h=hp
alias i=invite
# - j
alias k=man
alias l='ls -CF'
alias m='$MAILER'
# - n
alias o='$BROWSER'
alias p='$PAGER'
alias q=exit
alias r='R --quiet'
alias s='$SHELL'
alias t='type -a'
# - u
alias v='$VISUAL'
# + w - who is logged and what they do
# - x
# - y
# - z

alias ga='g a'
alias gc='g c'
alias gd='g d'
alias gl='g l'
alias gu='g update'
alias gp='g p'
alias gs='g s'
alias ka='killall -9'
alias la='ls -A'
alias ll='ls -ahlF'
alias py=python3
alias js=node
alias cf=compress
alias xf=extract

alias pls='sudo $(fc -ln -1)'
alias invite='2>/dev/null cd -P ~/.cache/i && rm ~/.cache/i || ln -s "$PWD" ~/.cache/i'
