#!/bin/sh

# Waiting for a command
if test "$SSH_CLIENT" -o "$SSH_TTY"; then
  PS1="[$USER@$(uname -n)]"' ${PWD##*/}$ '
else
  PS1='${PWD##*/}$ '
fi
# Waiting to complete command
PS2='> '  

# modify workstation (terminal) parameters
. "$HOME/.config/sh/tty"

# aliases
. "$HOME/.config/sh/aliases"

# functions
. "$HOME/.config/sh/functions"

# local configuration
test -f "$HOME/.shrc" && . "$HOME/.shrc"
