" Basic stuff
syntax on          " enable syntax processing
filetype plugin on " load filetype specific options 
set relativenumber " relative numbers
set cursorline     " line under the cursor
set colorcolumn=+1 " visual mark after textwidth column
set ruler          " show line and column
set number         " set line numbers
set shortmess+=I   " remove intro message
"set viminfo='100,<50,s10,h
"set spelllang=en,es,gl
"set showcmd
"set tabline=%N/\ %t\ %M
"set nocompatible
" colorscheme desert
" colorscheme elflord
" colorscheme slate

" Indentation
set backspace=2       " join lines when using backspace
set expandtab         " tabs to spaces
set shiftwidth=4      " Indent using 4 spaces
set softtabstop=4     " I do not know what this does
set autoindent        " add identation when you press <start>
set foldmethod=indent " fold things using identation
set formatoptions=c   " wrap only in commens

" Better search
set nomagic             " Only literals that must be escaped are \ and $
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
" set autochdir           " Change working directory to highlighted file see https://superuser.com/questions/604122/vim-file-name-completion-relative-to-current-file

" Working with several files
set wildmenu  " autocomplete menu
set hidden    " VIM does not complain when you open a new buffer 
set path+=**  " recursive search
set tags=./tags,tags;$HOME " search for file in folder and upwards til $HOME 

" Windows seems to open the wrong way
set splitbelow
set splitright

" Backup and swap files
set viminfo+=n~/.vim/viminfo
set directory^=$HOME/.vim/tmp//
set swapfile
set nobackup 

" misc
set timeoutlen=5000 " NOTE: Chefk if I should turn off timeout
" set listchars=tab:▸\ ,eol:¬ 

" Tag jumping (needs ctags)
command MakeTags !ctags -f tags -R .

" Set system clipboard as default register
" set clipboard=unnamedplus

" Backup and encryption
"set cryptmethod=blowfish2
"http://vim.wikia.com/wiki/Encryption
"https://stackoverflow.com/questions/575817/vim-encryption-how-to-break-it#575866

" Put cursor in the same place it was when we reopen a file
au BufReadPost *
 \ if line("'\"") > 1 && line("'\"") <= line("$") && &ft !~# 'commit'
 \ |   exe "normal! g`\""
 \ | endif

" Load fzf is possible
set rtp+=$FZF_HOME
packadd fzf.vim
