#!/bin/sh
# Technically this should be in .xprofile
# If this does not work with your distribution you could try to put this thing in .xsession, .xinitrc, or .profile_local


# GTK use Xorg compose key
export GTK_IM_MODULE=xim
export XMODIFIERS="@im=none"

# TODO: none of this seems to work
# TODO: Check that this works
# https://www.daniloaz.com/en/how-to-prevent-the-xsession-errors-file-from-growing-to-huge-size/
#ERRFILE=/dev/null
# TODO: Check if this works at all
# if command -v wmname >/dev/null 2>&1; then
#   # FOr no re-parenting window managers
#   # https://en.wikipedia.org/wiki/Re-parenting_window_manager
#   export _JAVA_AWT_WM_NONREPARTENTING=1
#   export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
#   # JDK programs (mostly swing) might fail even if you tell them bout
#   # reparenting.
#   # Make them think that they are in some old Sun 3D Desktop environment.
#   # https://tools.suckless.org/x/wmname/
#   wmname LG3D
# fi

# Make the keyboard repead delay and speed
#xset r rate 220 160
xset m 2 0
# Change layout to US International English
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
# Regular keyboard without Scroll_Lock/Pause/Break, most mod keys send special combination when tapped
xmodmap "$HOME/.config/x/modmap"
xcape -e 'ISO_Level3_Shift=Multi_key;Super_L=Control_L|space;Control_L=Caps_Lock;Shift_L=Escape'


# If we have redshift, we will use it
if command -v redshift >/dev/null 2>&1; then
  redshift >/dev/null 2>&1 &
fi
