#!/bin/sh
# Technically this should be in .xprofile, or maybe systemd
# If this does not work with your distribution you could try to put this thing in .xprofile, .xserverrc, .xsessionrc, .xinitrc, or .profile_local

# Set up most important config from shell
. "$HOME"/.config/sh/profile

# Use custom path X compose file
export XCOMPOSEFILE="$HOME"/.config/x/compose
# GTK use Xorg compose key
export GTK_IM_MODULE=xim
export XMODIFIERS="@im=none"

# TODO: none of this seems to work
#ERRFILE=/dev/null
# https://www.daniloaz.com/en/how-to-prevent-the-xsession-errors-file-from-growing-to-huge-size/

# Make the keyboard repead delay and speed
#xset r rate 220 160
xset m 2 0
# Change layout to US International English
setxkbmap -layout us -variant altgr-intl
# Regular keyboard without Scroll_Lock/Pause/Break, most mod keys send special combination when tapped
xmodmap "$HOME/.config/x/modmap"
xrdb -load "$HOME"/.config/x/resources
# xcape -e 'ISO_Level3_Shift=Multi_key;Super_L=Control_L|space;Control_L=Caps_Lock;Shift_L=Escape'
