#!/bin/sh
# Choose an action over over file with rifle
# I would like to do this with label = asker in rifle, but it is not working

rifle -l "$@"

printf '\nChoose a label:\n'

read -r ACTION

if test -z "$ACTION"; then
  printf 'No label provided.\n'
else
  rifle -p "$ACTION" "$@"
fi
