#!/usr/bin/env python3

import bs4
import click


@click.command()
@click.argument("input_file", type=click.File())
@click.argument("output_file", type=click.File(mode="w"), default=None)
def export_bookmarks(input_file, output_file):
    """Takes all links from a Firefox dump and inputs them in a plaintext format.
    """
    try:
        xml = bs4.BeautifulSoup(input_file, features="lxml")
    except:
        return click.echo("Couldnt not parse XML.", err=True)

    for link in xml.find_all("a"):
        click.echo(f"# {link.text}", file=output_file)
        click.echo(f'{link.attrs["href"]}', file=output_file)


if __name__ == "__main__":
    export_bookmarks()
