#!/bin/sh
# extract archive

if command -v rifle >/dev/null 2>&1; then
  rifle -p extractor "$@"
  exit $?
fi

for f in "$@"; do
  if [ -f "$f" ] ; then
    case "$f" in
      *.tar.bz2)   tar xjf "$f"   ;;
      *.tar.gz)    tar xzf "$f"   ;;
      *.bz2)       bunzip2 "$f"   ;;
      *.rar)       unrar x "$f"   ;;
      *.gz)        gunzip "$f"    ;;
      *.tar)       tar xf "$f"    ;;
      *.tbz2)      tar xjf "$f"   ;;
      *.tgz)       tar xzf "$f"   ;;
      *.zip)       unzip "$f"     ;;
      *.Z)         uncompress "$f";;
      *.7z)        7z x "$f"      ;;
      *)           printf '%s has an unrecognized file extension\n' "$f"
    esac
  else
    printf '%s is not a valid file\n' "$f" 1>&2
  fi
done

