#!/bin/sh
# scp, keep trying even if it fails

echo "Started $(date +'%F at %T')"
START=$(date +%s)

while true
do
  if rsync -Pavz "$@"
  then
    echo 'Done.'
    exit
  else
    echo 'Conexion failed, trying again in a minute.'
    sleep 60
  fi
done

echo "Finished $(date +'%F at %T')"
END=$(date +%s)

TIME=$((END - START))
printf 'It took %d days and %02d:%02d:%02d\n' $((TIME/86400)) $((TIME/3600)) $(((TIME%3600)/60)) $((TIME%60))
