#!/bin/sh
# All actions in the same executable

test "$(cat /proc/1/comm)" == systemd && logind=systemctl || logind=loginctl

case "$1" in
  lock)
    blurlock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    blurlock && $logind suspend
    ;;
  hibernate)
    blurlock && $logind hibernate
    ;;
  reboot)
    $logind reboot
    ;;
  shutdown)
    $logind poweroff
    ;;
  *)
    echo "== ! i3exit: missing or invalid argument ! =="
    echo "Try again with: lock | logout | suspend | hibernate | reboot | shutdown"
    exit 2
esac

exit 0

