#!/bin/sh
# Poor's man jrnl
# Read and write notes in ~/.notes

if test -v XDG_DATA_HOME; then
  FOLDER="$XDG_DATA_HOME/notes"
else
  FOLDER="$HOME/.notes"
fi

FILE="$FOLDER/${1:-default}"

mkdir -p "$FOLDER"

if [ ! -d "$FOLDER" ]
then
  printf '%s is not a directory!\n' "$FOLDER" 1>&2
  exit 1
fi

touch -a "$FILE"

$PAGER "$FILE"

find "$FOLDER" -empty -type f -delete 

find "$FOLDER" -type f -printf '%f\t%TY/%Tm/%Td %Tk:%TM\t%k\n' | \
  sort | \
  awk 'BEGIN {printf "Name Modificated (24h) Size (Kb)\n" }1' | \
  column -t 


