#!/bin/sh
# fires a qutebrowser script

script_dir=/usr/share/qutebrowser/scripts
userscript_dir=/usr/share/qutebrowser/userscripts

if [ ! -d "$script_dir" ] && [ -d "$userscript_dir" ]; then
  printf 'Could not find script folder' 1>&2
  exit 1
fi  

if [ $# -eq 0 ]; then
  find "$script_dir" "$userscript_dir" -executable -type f -exec basename {} \;
  exit $?
fi  

if [ -x "$script_dir/$1" ]; then
  "$script_dir/$@"
elif [ -x "$userscript_dir/$1" ]; then
  "$userscript_dir/$@"
else
  printf 'Could not find script' 1>&2
  exit 1
fi
