#!/bin/sh
# wrapper to task spooler to work with named task 

export TMPDIR="${TMPDIR:-/tmp}"

if [ "$#" -eq 0 ]; then
  print 'We need at least an argument (the ts socket queue)\n'
  exit 1
fi

QUEUE="$1"; shift

env TS_SOCKET="$TMPDIR/socket-ts.$QUEUE" ts "$@"
