#!/usr/bin/env bash
# actions over the clipboard
# FIXME: Copy paste with kitty
# FIXME: Copy paste with tmux buffers
# FIXME: Copy paste with piknik
# FIXME: Copy paste with temp files

TMPDIR="${TMPDIR:-/tmp}"
tmp_file="$TMPDIR/editor_$RANDOM" # NOTE: RANDOM breaks the POSIX compatibility

if command -v xsel > /dev/null; then
  cmd_input='xsel --clipboard --input'
  cmd_output='xsel --clipboard --output'
  cmd_append='xsel --clipboard --append'
  cmd_clear='xsel --clipboard --clear'
elif command -v pbcopy > /dev/null; then
  cmd_input='pbcopy'
  cmd_output='pbpaste'
  cmd_append='printf "append not implemented\n" 2>&1; false'
  cmd_clear='printf "" | pbcopy'
else
  printf 'Cannot find any program to interact with clipboard\n' 1>&2
  exit 1
fi

if command -v vipe > /dev/null; then
  cmd_edit="$0 -o | vipe | $0 -i"
elif [ -z "${VISUAL:-$EDITOR}" ]; then
  cmd_edit="$0 -o > $tmp_file; ${VISUAL:-$EDITOR} $tmp_file; $0 -i < $tmp_file"
else
  printf 'Could not find editor\n'
  exit 1
fi

case "$1" in
  '-i')
    eval "$cmd_input";;
  '-o')
    eval "$cmd_output";;
  '-a')
    eval "$cmd_append";;
  '-e')
    eval "$cmd_edit";;
  '-c')
    eval "$cmd_clear";;
  '-x')
    eval "$cmd_output" | "$SHELL";;
  *)
    printf 'You should use as first argument one of the following options:\n-i (input)\n-o (output)\n-a (append)\n-e (edit)\n-c (clear)\n-x execute\n' 1>&2
    exit 1
    ;;
esac
