" Basic stuff
" set nocompatible   " unlocks vim upgrades over vi, not needed usually
filetype plugin on " load filetype specific options 

" Visual options
syntax on          " enable syntax processing
set shortmess+=I   " remove intro message
set cursorline     " line under the cursor
set colorcolumn=+1 " visual mark after textwidth column
set number         " set line numbers
set relativenumber " relative numbers
set ruler          " show line and column
"set spelllang=en,es,gl
" colorscheme desert elflord slate

" Identation
set backspace=2       " join lines when using backspace
set expandtab         " tabs to spaces
set shiftwidth=4      " Indent using 4 spaces
set softtabstop=4     " I do not know what this does
set autoindent        " add identation when you press <start>
set foldmethod=indent " fold things using identation
set formatoptions=c,j " wrap only in commens

" Better search
set nomagic             " Only literals that must be escaped are \ and $
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
" set autochdir           " Change working directory to highlighted file see https://superuser.com/questions/604122/vim-file-name-completion-relative-to-current-file

" Command history
set history=5000

" Working with several files
set wildmenu  " autocomplete menu
set hidden    " VIM does not complain when you open a new buffer 
set path+=**  " recursive search
set tags=./tags,tags;$HOME " search for file in folder and upwards til $HOME 
" TODO: See how to make this work in macOS
" set diffopt+=internal,algorithm:patience " Uses patience intead of myers with xdiff

" Windows seems to open the wrong way
set splitbelow
set splitright

" Backup and swap files
set viminfo+=n~/.vim/viminfo
set directory^=$HOME/.vim/tmp//
set swapfile
" set writebackup # if you want to write a backup during the write
" set backupdir^=~/.vim/backup//
" set backupcopy=auto " rename and write when save
set nobackup 
" set undofile " persist the undo tree for each file
" set undodir^=~/.vim/undo//

" misc
set timeoutlen=5000 " NOTE: Chefk if I should turn off timeout
set lazyredraw      " TODO: check if this improve things
set virtualedit=all " Move to places without characters
set nostartofline " stop changing the cursor when I fire a command
" set listchars=tab:▸\ ,eol:¬ 
"  set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
" set encoding=utf-8
set autoread " read files on change
" set autowrite " write when  moving from file

" Set system clipboard as default register
" set clipboard=unnamedplus

" Backup and encryption
"set cryptmethod=blowfish2
"http://vim.wikia.com/wiki/Encryption
"https://stackoverflow.com/questions/575817/vim-encryption-how-to-break-it#575866

" Put cursor in the same place it was when we reopen a file
au BufReadPost *
 \ if line("'\"") > 1 && line("'\"") <= line("$") && &ft !~# 'commit'
 \ |   exe "normal! g`\""
 \ | endif
