" Backup and swap files
set nocompatible
" TODO: Set this with XDG or turn off
" TODO: This will fail unless the directory exists in advance
set history=5000                           " increase history commands
set viminfo+=n~/.local/share/vim/viminfo   " where to save history
set directory^=~/.local/share/vim/swap//   " where to save swap files
" TODO: Double check if you backups at all
set backupdir^=~/.local/share/vim/backup// " where to store temporary backups
" set nobackup
" set noundofile
" Do not assume that leading zeroes means an octal
set nrformats-=octal

set rtp+=/usr/share/doc/fzf/examples/plugin/

call plug#begin()
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf'
call plug#end()

